### PR TITLE
Add new blurbs to Who's Using VWF section.

### PR DESCRIPTION
**Pull request by allisoncorey**
@marktorpey @rchadwic 

Please review for accuracy.

### CODE REVIEW

**Comment by rchadwic** [comment]
My only comment is to capitalize the first C in the Cosmos3D section.

**Comment by marktorpey** [comment]
Looks good to me.

Rob, do you think any of the organizations will wish to review before we go live?  If so, can you ask them to review?

I’ll check with DAS about Wearality.

**Comment by nmarshak1337** [comment]
Apologies in advance for being a Grammar Nazi... :-P

I'm pleased that these people are using VWF! These blurbs are great, but I love to nitpick:

> Citizens Foundation created an app entitled Your Priorities 3D to bring people together in real time virtual reality workshops, as part of the Better Reykjavik Pracipatory budgeting.

Consider splitting this sentence, since it is rather long. I think "Pracipatory" should be spelled "Participatory". Should "budgeting" be capitalized? Also, "the the Better Reykjavik Pracipatory budgeting" sounds... a little strange, I believe because "budgeting" is a verb. Is there a noun that could be added to the end, e.g. "budgeting act"? Or, "the" can be removed. 

> Each neighborhood had its own workshop, where over 300 total citizens participated creating multimedia presentations for new ideas.

Consider changing "had" to "held". Also consider removing "total" - it's implicit that 300 is a total. I think there should be a comma between "participated" and "creating". "Each neighborhood" could be a little more specific. Each neighborhood in Iceland? In Reykjavík? Adding just one more noun could add a lot of meaning to the sentence. Even "Each participating neigbhorhood" sounds a little better. Finally, "for new ideas" could be rephrased - it could be replaced with something that has different ring - e.g. "creating multimedia presentations that expressed their ideas". 

> Users can create persistent worlds and collaborate in realtime with others

In the "Citizens Foundation of Iceland" blurb, "realtime" is two words, whereas here it is one word. We should pick a single convention and stick with it. 

> Additionally, the platform has a virtual currency system and asset marketplace that provides professionals and hobby artists the opportunity to earn real money from selling their creations to other users.

Consider splitting / shortening this sentence. IMHO, "professional artists and hobbyists" sounds better than "professionals and hobby artists" - perhaps because I've heard the former phrasing more often than the latter. Also, consider changing "provides" to a different word - you use "provides" in the previous sentence.

> Universidade Federal da Grande Dourados (UFGD) is building a physics lab app, allowing for students to type in an angle, force, and weight and plot an associated parabola, to eventually be integrated into a Moodle-based distance learning course for approximately 400 students.

Again, consider splitting. A good split point, IMHO, would be to change "parabola, to eventually be integrated" to "parabola. The app will eventually be integrated"... Perhaps you could change the sentence to avoid putting two ANDs in very close proximity (in "and weight and plot").

**Comment by rchadwic** [comment]
What's the update cycle look like? If it's just a week or so, I say put it
up and we can let them review on the live site. Sometimes getting something
out there is the only way to force them to make a decision.

On Wed, Jan 28, 2015 at 7:14 PM, marktorpey <notifications@github.com>
wrote:

> Looks good to me.
>
> Rob, do you think any of the organizations will wish to review before we
> go live? If so, can you ask them to review?
>
> I’ll check with DAS about Wearality.
>
>
> From: rchadwic [mailto:notifications@github.com]
> Sent: Wednesday, January 28, 2015 6:19 PM
> To: virtual-world-framework/vwf-web
> Cc: Torpey, Mark
> Subject: EXTERNAL: Re: [vwf-web] Add new blurbs to Who's Using VWF
> section. (#41)
>
>
> My only comment is to capitalize the first C in the Cosmos3D section.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/virtual-world-framework/vwf-web/pull/41#issuecomment-71937877>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/virtual-world-framework/vwf-web/pull/41#issuecomment-71944622>
> .
>



-- 




*Rob ChadwickAdvance Distributed Learningrobert.chadwick.ctr@adlnet.gov
<robert.chadwick.ctr@adlnet.gov>703-575-2012*

**Comment by allisoncorey** [comment]
Thanks, @nmarshak1337 . I'll integrate some comments today. 

@rchadwic We don't have a regular update cycle, the site is now updated on an as-needed basis. If there are no additional comments, I will go ahead and push today, and we can make changes as needed. Thanks!

**Comment by rchadwic** [comment]
For reference, Stefan from Cosmos suggests 

> Cosmos3d.com is a free to play virtual World platform and social community where 3D Worlds are >
>  created by its Users.

**Comment by digitaledge** [comment]
I couldnt describe cosmos3d better, this is absolutely ok from my side.

Regards

Stefan

**Comment by allisoncorey** [comment]
FYI, the latest demos page is live: https://virtual.wf/demos.html. Please let me know if there are any additional comments. Thanks!

**Pull request merged**
