### PR TITLE
Update mars-game link on VWF website.

### PR DESCRIPTION
**Pull request by allisoncorey**
@kadst43

### CODE REVIEW

**Comment by kadst43** [comment]
:+1: 

(But click the link and make sure it works first :) )

**Comment by allisoncorey** [comment]
Well it generated a session... but doesn't load on our network as it isn't over SSL. Any chance you have an https link?

**Comment by kadst43** [comment]
The same addy with https should work, but it gives scary-sounding security warnings.

**Comment by allisoncorey** [comment]
Yeah, I think that's why we dropped the https in the first place. I'll leave it at http for now. Thanks!

**Pull request merged**
